# Exported from Render on 2025-06-11T11:03:44Z
services:
- type: web
  name: tb-detection-3
  runtime: python
  repo: https://github.com/iampiyushchouhan/tb-detection
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: streamlit run streamlit_app.py --server.port=$PORT --server.address=0.0.0.0
  autoDeployTrigger: commit
version: "1"
